### ISSUE TITLE
Remove DO-specific configurations 

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-sdks#10]
Configurations specific to the Data Observatory should ultimately be removed from the Python SDK, which should be able to get everything it needs from OVE Core using its APIs.

However, a major part of the Data Observatory specific configurations is the list of port numbers.

This transition is therefore blocked until we start proxying our microservices properly, rather than assigning them to a port range that differs between installations.

**Comment by senakafdo** [comment]
This issue is no longer blocked as the apps are now listed under `http://OVE_CORE_HOST:PORT/app/OVE_APP_NAME`. Please do get rid of all non-local configurations found in [here](https://github.com/ove/ove-sdks/blob/master/python/ove/config.py). Those do not make sense for an end-user.

Please also remove names of spaces and their dimensions from the configuration. These need not be hardcoded in the OVE SDK as they can be obtained using the OVE APIs. The only requirement for the end user would be to provide the port at which OVE is running and it should default to 8080.

**Comment by senakafdo** [comment]
@jamesscottbrown, I am affraid the issue is not yet fully resolved. Can we get rid of the dodev and doprod specifications altogether please?
